[2021-11-20 18:15:33,541: INFO: 01_base_model_creation]: 
********************
[2021-11-20 18:15:33,542: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-20 18:15:33,542: ERROR: 01_base_model_creation]: main() missing 1 required positional argument: 'params_path'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config)
TypeError: main() missing 1 required positional argument: 'params_path'
[2021-11-20 18:15:53,388: INFO: 01_base_model_creation]: 
********************
[2021-11-20 18:15:53,388: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-20 18:15:53,389: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-20 18:15:55,579: ERROR: 01_base_model_creation]: module 'keras.api._v2.keras' has no attribute 'optimizer'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 51, in main
    OPTIMIZER = tf.keras.optimizer.SGD(learning_rate=1e-3)
AttributeError: module 'keras.api._v2.keras' has no attribute 'optimizer'
[2021-11-20 18:16:13,170: INFO: 01_base_model_creation]: 
********************
[2021-11-20 18:16:13,170: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-20 18:16:13,171: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-20 18:16:14,248: ERROR: 01_base_model_creation]: Invalid keyword argument(s) in `compile()`: ({'metric'},). Valid keyword arguments include "cloning", "experimental_run_tf_function", "distribute", "target_tensors", or "sample_weight_mode".
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 54, in main
    model.compile(loss=LOSS, optimizer=OPTIMIZER, metric=METRICS)
  File "D:\LIVE_CLASS\DLVNLP_AUG\Transfer_learning_DLCVNLP_demo\env\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\LIVE_CLASS\DLVNLP_AUG\Transfer_learning_DLCVNLP_demo\env\lib\site-packages\keras\engine\training.py", line 2786, in _validate_compile
    raise TypeError('Invalid keyword argument(s) in `compile()`: '
TypeError: Invalid keyword argument(s) in `compile()`: ({'metric'},). Valid keyword arguments include "cloning", "experimental_run_tf_function", "distribute", "target_tensors", or "sample_weight_mode".
[2021-11-20 18:16:29,377: INFO: 01_base_model_creation]: 
********************
[2021-11-20 18:16:29,377: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-20 18:16:29,378: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-20 18:16:30,492: INFO: 01_base_model_creation]: >>>>> stage creating base model completed!<<<<<

